[2022-12-11 19:20:50,445] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-19T15:00:00+00:00 [queued]>
[2022-12-11 19:20:50,666] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-19T15:00:00+00:00 [queued]>
[2022-12-11 19:20:50,670] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:50,695] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-11 19:20:50,706] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:51,139] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_etl_process> on 2022-11-19 15:00:00+00:00
[2022-12-11 19:20:51,206] {standard_task_runner.py:52} INFO - Started process 303 to run task
[2022-12-11 19:20:51,289] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_DAG', 'run_etl_process', 'scheduled__2022-11-19T15:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/etl_DAG.py', '--cfg-path', '/tmp/tmp_dxurebg', '--error-file', '/tmp/tmpkuapznm_']
[2022-12-11 19:20:51,328] {standard_task_runner.py:80} INFO - Job 214: Subtask run_etl_process
[2022-12-11 19:20:52,949] {task_command.py:369} INFO - Running <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-19T15:00:00+00:00 [running]> on host 0163e0790208
[2022-12-11 19:20:54,938] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_DAG
AIRFLOW_CTX_TASK_ID=run_etl_process
AIRFLOW_CTX_EXECUTION_DATE=2022-11-19T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-19T15:00:00+00:00
[2022-12-11 19:21:50,888] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 19:21:52,717] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_DAG, task_id=run_etl_process, execution_date=20221119T150000, start_date=20221211T192050, end_date=20221211T192152
[2022-12-11 19:21:53,501] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-11 19:21:53,691] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 303. PIDs of all processes in the group: [303]
[2022-12-11 19:21:53,757] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 303
[2022-12-11 19:21:54,138] {process_utils.py:75} INFO - Process psutil.Process(pid=303, status='terminated', exitcode=0, started='19:20:50') (303) terminated with exit code 0
