[2022-11-06 14:02:17,529] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:04:00+00:00 [queued]>
[2022-11-06 14:02:17,586] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:04:00+00:00 [queued]>
[2022-11-06 14:02:17,594] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:02:17,595] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-11-06 14:02:17,617] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:02:17,751] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_xetra_etl> on 2022-11-03 20:04:00+00:00
[2022-11-06 14:02:19,477] {standard_task_runner.py:52} INFO - Started process 108 to run task
[2022-11-06 14:02:20,262] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xetra_DAG', 'run_xetra_etl', 'scheduled__2022-11-03T20:04:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/xetra_DAG.py', '--cfg-path', '/tmp/tmpsz9ics7p', '--error-file', '/tmp/tmpb0h502in']
[2022-11-06 14:02:20,277] {standard_task_runner.py:80} INFO - Job 147: Subtask run_xetra_etl
[2022-11-06 14:02:34,152] {task_command.py:369} INFO - Running <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:04:00+00:00 [running]> on host 0163e0790208
[2022-11-06 14:03:40,803] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xetra_DAG
AIRFLOW_CTX_TASK_ID=run_xetra_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T20:04:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T20:04:00+00:00
[2022-11-06 14:05:24,011] {python.py:173} INFO - Done. Returned value was: None
[2022-11-06 14:05:24,074] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xetra_DAG, task_id=run_xetra_etl, execution_date=20221103T200400, start_date=20221106T140217, end_date=20221106T140524
[2022-11-06 14:05:24,940] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-06 14:05:25,008] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 108. PIDs of all processes in the group: [108]
[2022-11-06 14:05:25,025] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 108
[2022-11-06 14:05:25,057] {process_utils.py:75} INFO - Process psutil.Process(pid=108, status='terminated', exitcode=0, started='14:02:18') (108) terminated with exit code 0
