[2022-12-11 19:20:39,639] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-25T15:00:00+00:00 [queued]>
[2022-12-11 19:20:40,256] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-25T15:00:00+00:00 [queued]>
[2022-12-11 19:20:40,285] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:40,286] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-12-11 19:20:40,287] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-11 19:20:41,009] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_etl_process> on 2022-11-25 15:00:00+00:00
[2022-12-11 19:20:41,139] {standard_task_runner.py:52} INFO - Started process 288 to run task
[2022-12-11 19:20:41,320] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_DAG', 'run_etl_process', 'scheduled__2022-11-25T15:00:00+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/etl_DAG.py', '--cfg-path', '/tmp/tmp5poq86s5', '--error-file', '/tmp/tmplk0bllli']
[2022-12-11 19:20:41,370] {standard_task_runner.py:80} INFO - Job 211: Subtask run_etl_process
[2022-12-11 19:20:43,468] {task_command.py:369} INFO - Running <TaskInstance: etl_DAG.run_etl_process scheduled__2022-11-25T15:00:00+00:00 [running]> on host 0163e0790208
[2022-12-11 19:20:47,627] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_DAG
AIRFLOW_CTX_TASK_ID=run_etl_process
AIRFLOW_CTX_EXECUTION_DATE=2022-11-25T15:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-25T15:00:00+00:00
[2022-12-11 19:21:50,307] {python.py:173} INFO - Done. Returned value was: None
[2022-12-11 19:21:52,877] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_DAG, task_id=run_etl_process, execution_date=20221125T150000, start_date=20221211T192039, end_date=20221211T192152
[2022-12-11 19:21:53,896] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-12-11 19:21:54,767] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 288. PIDs of all processes in the group: [288]
[2022-12-11 19:21:54,874] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 288
[2022-12-11 19:21:55,234] {process_utils.py:75} INFO - Process psutil.Process(pid=288, status='terminated', exitcode=0, started='19:20:40') (288) terminated with exit code 0
