[2022-11-06 14:06:49,257] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:01:00+00:00 [queued]>
[2022-11-06 14:06:49,280] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:01:00+00:00 [queued]>
[2022-11-06 14:06:49,280] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:06:49,281] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-11-06 14:06:49,281] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:07:00,338] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_xetra_etl> on 2022-11-03 20:01:00+00:00
[2022-11-06 14:07:04,628] {standard_task_runner.py:52} INFO - Started process 164 to run task
[2022-11-06 14:07:04,637] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xetra_DAG', 'run_xetra_etl', 'scheduled__2022-11-03T20:01:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/xetra_DAG.py', '--cfg-path', '/tmp/tmpvgnfxmbp', '--error-file', '/tmp/tmp3ab0zpd5']
[2022-11-06 14:07:12,895] {standard_task_runner.py:80} INFO - Job 158: Subtask run_xetra_etl
[2022-11-06 14:07:15,070] {task_command.py:369} INFO - Running <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-03T20:01:00+00:00 [running]> on host 0163e0790208
[2022-11-06 14:07:47,973] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xetra_DAG
AIRFLOW_CTX_TASK_ID=run_xetra_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-11-03T20:01:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-03T20:01:00+00:00
[2022-11-06 14:07:56,029] {python.py:173} INFO - Done. Returned value was: None
[2022-11-06 14:07:57,056] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xetra_DAG, task_id=run_xetra_etl, execution_date=20221103T200100, start_date=20221106T140649, end_date=20221106T140757
[2022-11-06 14:07:57,776] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-11-06 14:07:57,784] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 164. PIDs of all processes in the group: [164]
[2022-11-06 14:07:57,787] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 164
[2022-11-06 14:07:59,888] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-11-06 14:07:59,950] {process_utils.py:75} INFO - Process psutil.Process(pid=164, status='terminated', exitcode=0, started='14:07:03') (164) terminated with exit code 0
